Changes to et.json
MrBartusek/MeteoalarmCard pull request #24
Opened 2021-05-24 08:20 UTC by Repsionu

Best, JR

2021-05-24 10:10 UTC, MrBartusek requested changes

2021-05-24 10:10 UTC, MrBartusek commented on src/translations/et.json
>    },
Invalid indent

2021-05-24 10:10 UTC, MrBartusek commented on src/translations/et.json
> +
No empty line needed

2021-05-24 10:10 UTC, MrBartusek commented on src/translations/et.json
>    }
As I said, if you think that card is not properly displayed please create an issue indeed of changing translation files

2021-05-25 08:17 UTC, closed without merging

2021-05-25 08:18 UTC, Repsionu commented
Thanks, next time will try not to mess up...