Update dutch
MrBartusek/MeteoalarmCard pull request #66
Opened 2022-01-20 11:06 UTC by BartEngelen

2022-01-20 11:17 UTC, MrBartusek requested changes
Hey, Thanks for the PR!

However, your `master` branch is outdated and the translation files have been updated a couple of times since then. Please do rebase your `master` and work on the new files.

2022-01-20 12:19 UTC, BartEngelen commented
Hello,
Can you help me on this one ?
Kind regards,
Bart Engelen

2022-01-20 20:57 UTC, MrBartusek commented
You can try using this button on your fork and then rebasing once again 
![image](https://user-images.githubusercontent.com/23432278/150420971-a997fc57-e60d-4759-97ef-f7653ee7faf4.png)

2022-01-21 09:35 UTC, BartEngelen commented
Hello,
I got this error:
![image](https://user-images.githubusercontent.com/17978789/150503180-c5586d74-e3e3-440a-aded-149ce94893e8.png)
What can I do to fix this ?
Regards,
Bart Engelen

2022-01-21 09:54 UTC, MrBartusek commented
You are still working on an old version of master

2022-02-11 14:10 UTC, MrBartusek commented
There hasn't been any activity in this pull request recently so I will close it. Feel free to create a new one if you want to continue your work. Thanks for your contribution!

2022-02-11 14:10 UTC, closed without merging

2022-04-06 08:18 UTC, MDLefevere reviewed
These 3 lines need to be changed for the right text.

2022-04-06 08:18 UTC, MDLefevere commented on src/translations/nl.json
> -    "yellow": "Waarschuwing geel {0}",
"Code Geel: {0}"

2022-04-06 08:18 UTC, MDLefevere commented on src/translations/nl.json
> -    "orange": "Waarschuwing oranje {0}",
"Code Oranje: {0}"

2022-04-06 08:18 UTC, MDLefevere commented on src/translations/nl.json
> -    "red": "Waarschuwing rood {0}"
"Code Rood: {0}"